# Topic: Vectorizing 

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer(binary=True)

corpus=["NLP is awesome","I want to start aN NLP Company","Top unicorns use NLP"]

In [2]:
vect.fit(corpus)

CountVectorizer(binary=True)

In [3]:
vocab=vect.vocabulary_  #Attribute

In [4]:
for key in sorted(vocab.keys()):
    print("{}:{}".format(key,vocab[key]))

an:0
awesome:1
company:2
is:3
nlp:4
start:5
to:6
top:7
unicorns:8
use:9
want:10


In [5]:
vect.transform(["I have an awesome NLP Company worth an awesome billion"]).toarray

<bound method _cs_matrix.toarray of <1x11 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>>

In [6]:
vect.transform(["I have an awesome NLP Company worth an awesome billion"]).toarray()

array([[1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [13]:
vect.transform(["NLP is an elective subject"]).toarray()

array([[1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [15]:
vect.transform(["ML is an elective subject"]).toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [11]:
vect.transform(["NLP is an attractive career now"]).toarray()

array([[1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
similarity = cosine_similarity(vect.transform(["NLP is an elective subject"]).toarray(), vect.transform(["NLP is an attractive career now"]).toarray())
similarity

array([[1.]])

In [14]:
similarity = cosine_similarity(vect.transform(["ML is an elective subject"]).toarray(), vect.transform(["NLP is an attractive career now"]).toarray())
similarity

array([[0.81649658]])